# -*- coding: utf-8 -*-
"""notebook71f3b5a8cd (11).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Ii9kq7nMTjTEBYvBOLoJcQUSHb-PZfN
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Update this path to match your dataset
ROOT_DIR = "/kaggle/input/dal-shemagh-detection-challenge"
WORK_DIR = "./yolo_data"

print(f"Dataset directory: {ROOT_DIR}")
print(f"Working directory: {WORK_DIR}")

# Load training labels
train_df = pd.read_csv(os.path.join(ROOT_DIR, "train_labels.csv"))
print(f"Training images: {len(train_df)}")
print("\nFirst few rows:")
display(train_df.head())

!pip install -q ultralytics

import shutil


import pandas as pd
from pathlib import Path
from ultralytics import YOLO
from sklearn.model_selection import train_test_split
from tqdm import tqdm

# Split into train (80%) and validation (20%)
train_data, val_data = train_test_split(
    train_df,
    test_size=0.2,
    random_state=42,
    stratify=train_df['right_place']
)

print(f"Train set: {len(train_data)} images")
print(f"Validation set: {len(val_data)} images")

print("Train distribution:\n", train_data['right_place'].value_counts())
print("\nVal distribution:\n", val_data['right_place'].value_counts())

for split in ['train', 'val']:
    os.makedirs(f"{WORK_DIR}/images/{split}", exist_ok=True)
    os.makedirs(f"{WORK_DIR}/labels/{split}", exist_ok=True)

def prepare_yolo_split(df, split_name):
    """Copy images and labels to YOLO format directories"""
    print(f"\nPreparing {split_name} set...")

    for _, row in tqdm(df.iterrows(), total=len(df)):
        filename = row['filename']
        stem = Path(filename).stem

        # Copy image
        src_img = os.path.join(ROOT_DIR, "images/train", filename)
        dst_img = os.path.join(WORK_DIR, f"images/{split_name}", filename)
        shutil.copy(src_img, dst_img)

        # Copy label (create empty if doesn't exist)
        src_lbl = os.path.join(ROOT_DIR, "labels/train", f"{stem}.txt")
        dst_lbl = os.path.join(WORK_DIR, f"labels/{split_name}", f"{stem}.txt")

        if os.path.exists(src_lbl):
            shutil.copy(src_lbl, dst_lbl)
        else:
            # Empty label = no objects in image
            open(dst_lbl, 'w').close()

# Prepare both splits
prepare_yolo_split(train_data, 'train')
prepare_yolo_split(val_data, 'val')

print("\n✓ YOLO directories ready!")

# import torch
# from torch.utils.data import Dataset, DataLoader
# from torchvision import transforms
# from torchvision.models.detection import detr_resnet50
# import os
# from PIL import Image
# import json

# # إعداد Dataset لـ DETR
# class CustomDETRDataset(Dataset):
#     def __init__(self, images_dir, annotations, transforms=None):
#         self.images_dir = images_dir
#         self.annotations = annotations  # List of dicts: {image_id, boxes, labels}
#         self.transforms = transforms

#     def __len__(self):
#         return len(self.annotations)

#     def __getitem__(self, idx):
#         ann = self.annotations[idx]
#         img_path = os.path.join(self.images_dir, ann['image_id'])
#         img = Image.open(img_path).convert("RGB")

#         boxes = torch.tensor(ann['boxes'], dtype=torch.float32)  # [[x_min, y_min, x_max, y_max], ...]
#         labels = torch.tensor(ann['labels'], dtype=torch.int64)

#         target = {"boxes": boxes, "labels": labels}

#         if self.transforms:
#             img = self.transforms(img)

#         return img, target

# # مثال لتهيئة البيانات
# train_annotations = [
#     {"image_id": "img1.jpg", "boxes": [[50, 30, 200, 180]], "labels": [1]},
#     # أضف باقي الصور هنا
# ]

# val_annotations = [
#     {"image_id": "img2.jpg", "boxes": [[20, 40, 100, 120]], "labels": [2]},
# ]

# transform = transforms.Compose([
#     transforms.Resize((640, 640)),
#     transforms.ToTensor()
# ])

# train_dataset = CustomDETRDataset("images/train", train_annotations, transforms=transform)
# val_dataset = CustomDETRDataset("images/val", val_annotations, transforms=transform)

# train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True, collate_fn=lambda x: tuple(zip(*x)))
# val_loader = DataLoader(val_dataset, batch_size=8, shuffle=False, collate_fn=lambda x: tuple(zip(*x)))

# # تحميل موديل DETR
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# model = detr_resnet50(num_classes=3)  # nc=2 + background
# model.to(device)

# # Optimizer
# optimizer = torch.optim.AdamW(model.parameters(), lr=0.003)

# # Training loop بسيط
# num_epochs = 50
# for epoch in range(num_epochs):
#     model.train()
#     for imgs, targets in train_loader:
#         imgs = list(img.to(device) for img in imgs)
#         targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

#         loss_dict = model(imgs, targets)
#         losses = sum(loss for loss in loss_dict.values())

#         optimizer.zero_grad()
#         losses.backward()
#         optimizer.step()

#     print(f"Epoch {epoch+1}/{num_epochs} done, loss: {losses.item():.4f}")

yaml_content = f"""path: {os.path.abspath(WORK_DIR)}
train: images/train
val: images/val

nc: 2
names: ['Face', 'Shemagh']
"""

with open(f"{WORK_DIR}/data.yaml", "w") as f:
    f.write(yaml_content)

print("✓ Configuration created!")
print("\nContent:")
print(yaml_content)

# import os
# import glob
# import matplotlib.pyplot as plt

# # مسار ملفات ال labels
# labels_path = "/kaggle/input/dal-shemagh-detection-challenge/labels/train"

# # جلب كل ملفات txt
# label_files = glob.glob(os.path.join(labels_path, "*.txt"))

# # Counters
# images_with_person = 0
# images_with_shemagh = 0
# images_with_any_object = 0
# images_without_object = 0

# for file in label_files:
#     has_person = False
#     has_shemagh = False

#     with open(file, 'r') as f:
#         lines = f.readlines()
#         for line in lines:
#             cls = int(line.split()[0])
#             if cls == 0:
#                 has_person = True
#             elif cls == 1:
#                 has_shemagh = True

#     if has_person:
#         images_with_person += 1
#     if has_shemagh:
#         images_with_shemagh += 1
#     if has_person or has_shemagh:
#         images_with_any_object += 1
#     else:
#         images_without_object += 1

# # Diagram
# labels = ['Images with Person', 'Images with Shemagh', 'Images with Any Object', 'Images without Object']
# counts = [images_with_person, images_with_shemagh, images_with_any_object, images_without_object]

# plt.figure(figsize=(10,5))
# plt.bar(labels, counts, color=['skyblue', 'salmon', 'lightgreen', 'lightgrey'])
# plt.title('Distribution of images by object presence')
# plt.ylabel('Number of images')
# plt.show()

# # Print percentages
# total_images = len(label_files)
# for label, count in zip(labels, counts):
#     print(f"{label}: {count} images ({count/total_images*100:.2f}%)")

from ultralytics import YOLO
import matplotlib.pyplot as plt

# Load YOLOv8 model (small version)
# model = YOLO("yolo11s.pt")

from ultralytics import RTDETR

from ultralytics import RTDETR

model = RTDETR("rtdetr-l.pt")

results = model.train(
    data=f"{WORK_DIR}/data.yaml",
    epochs=100,
    imgsz=512,
    batch=8,
    project='dal_challenge',
    name='shemagh_detector_rtdetr',
    exist_ok=True,
    mosaic=1.0,
    copy_paste=0.8,
    scale=0.5,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    fliplr=0.5,
    flipud=0.3,
    lr0=0.0005,  # أقل من YOLO
    lrf=0.2
)

# تقييم
metrics = model.val(save_json=True, plots=True)
0.4618
print(f"mAP@0.5‑0.95: {metrics.box.map:.4f}")
print(f"mAP@0.5: {metrics.box.map50:.4f}")
print(f"mAP@0.75: {metrics.box.map75:.4f}")



# # Load an image and run inference
# results = model(base + "/images/test/0.jpg", save=True)

# # Convert result to a NumPy array and display
# predicted_image = results[0].plot()  # Convert prediction to an image

# plt.figure(figsize=(16, 16))
# plt.imshow(predicted_image)
# plt.axis("off")
# plt.title("Predicted Image")
# plt.show()

# import albumentations as A

# my_transform = A.Compose([
#     # A.Resize((640, 640)),
#     A.HorizontalFlip(p=0.5),
#     A.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1),
#     A.GaussianBlur(p=0.1),
#     A.Rotate(limit=10),
# ])

# from ultralytics import YOLO

# yolo = YOLO('yolov8s.pt')  # Small

# results = yolo.train(
#     data=f"{WORK_DIR}/data.yaml",
#     epochs=10,          # زيادة عدد epochs
#     imgsz=640,
#     batch=8,
#     project='dal_challenge',
#     name='shemagh_detector_s',
#     exist_ok=True,
#     mosaic=1.0,
#     copy_paste=0.8,
#     scale=0.5,          # رؤية objects أصغر
#     hsv_h=0.015,
#     hsv_s=0.7,
#     hsv_v=0.4,
#     fliplr=0.5,
#     flipud=0.3,

# )

# metrics = yolo.val(save_json=True, save_hybrid=True, plots=True)

# print("\n" + "="*60)
# print("VALIDATION RESULTS")
# print("="*60)
# print(f"mAP@0.5:0.95: {metrics.box.map:.4f}")
# print(f"mAP@0.5:     {metrics.box.map50:.4f}")
# print(f"mAP@0.75:    {metrics.box.map75:.4f}")
# print("="*60)

# # 2. Define a function to calculate IoU (Intersection over Union)
# def calculate_iou(box1, box2):
#     """
#     Calculate IoU between two boxes (x, y, w, h normalized).
#     """
#     # Convert from xywh to x1, y1, x2, y2
#     b1_x1, b1_x2 = box1[0] - box1[2]/2, box1[0] + box1[2]/2
#     b1_y1, b1_y2 = box1[1] - box1[3]/2, box1[1] + box1[3]/2

#     b2_x1, b2_x2 = box2[0] - box2[2]/2, box2[0] + box2[2]/2
#     b2_y1, b2_y2 = box2[1] - box2[3]/2, box2[1] + box2[3]/2

#     # Intersection coordinates
#     inter_x1 = max(b1_x1, b2_x1)
#     inter_y1 = max(b1_y1, b2_y1)
#     inter_x2 = min(b1_x2, b2_x2)
#     inter_y2 = min(b1_y2, b2_y2)

#     inter_area = max(0, inter_x2 - inter_x1) * max(0, inter_y2 - inter_y1)
#     b1_area = (b1_x2 - b1_x1) * (b1_y2 - b1_y1)
#     b2_area = (b2_x2 - b2_x1) * (b2_y2 - b2_y1)

#     union_area = b1_area + b2_area - inter_area
#     return inter_area / union_area if union_area > 0 else 0

# # !ls /kaggle/working/
# ls = RTDETR("/kaggle/working/runs/detect/dal_challenge/shemagh_detector_rtdetr/weights/best.pt")

import glob

# 1. Setup paths
vall_images = glob.glob(
    f'{WORK_DIR}/images/val/*.jpg')
submission_data = []


print(f"Processing {len(vall_images)} images...")

# 3. Inference Loop
# print(f"Processing {len(test_images)} images...")

for img_path in tqdm(vall_images):
    filename = os.path.basename(img_path)

    # Run inference
    results = model.predict(img_path, conf=0.25, verbose=False)[0]

    prediction_strings = []
    person_boxes = []
    shemagh_boxes = []

    # Process detections
    if len(results.boxes) == 0:
        prediction_str = "-"
        right_place = 0
    else:
        for box in results.boxes:
            # Extract data
            cls = int(box.cls[0])
            conf = float(box.conf[0])

            # YOLO returns xywh normalized if we access .xywhn
            x, y, w, h = box.xywhn[0].tolist()

            # Append to prediction string
            prediction_strings.append(f"{cls} {conf:.4f} {x:.4f} {y:.4f} {w:.4f} {h:.4f}")

            # Store boxes for logic check
            if cls == 0: # Assuming 0 is Person
                person_boxes.append([x, y, w, h])
            elif cls == 1: # Assuming 1 is Shemagh
                shemagh_boxes.append([x, y, w, h])

        prediction_str = " ".join(prediction_strings)

        # --- LOGIC FOR "RIGHT PLACE" ---
        # Heuristic: If we found at least one person and one shemagh
        # and they overlap (IoU > threshold), predict 1.

        right_place = 0 # Default to 0
        if person_boxes and shemagh_boxes:
            # Check every shemagh against every person
            for s_box in shemagh_boxes:
                for p_box in person_boxes:
                    iou = calculate_iou(s_box, p_box)
                    # Threshold: 0.1 means 10% overlap. Adjust this based on validation!
                    if iou > 0.1:
                        right_place = 1
                        break
                if right_place == 1:
                    break

    submission_data.append([filename, right_place, prediction_str])

# 4. Save to CSV
df_sub = pd.DataFrame(submission_data, columns=['filename', 'right_place', 'prediction_string'])
df_sub.to_csv('submission.csv', index=False)

print("Submission.csv generated successfully!")
print(df_sub.head(20))

from sklearn.metrics import f1_score, precision_score, recall_score, classification_report

val_data['right_place'] = val_data['right_place'].astype(int)
df_sub['right_place'] = df_sub['right_place'].astype(int)

gt_dict = dict(zip(val_data['filename'], val_data['right_place']))

y_true = []
y_pred = []

for _, row in df_sub.iterrows():
    filename = row['filename']

    if filename in gt_dict:   # 🔥 هذا هو الحل
        y_true.append(gt_dict[filename])
        y_pred.append(row['right_place'])

print("F1-score :", f1_score(y_true, y_pred))
print("Precision:", precision_score(y_true, y_pred))
print("Recall   :", recall_score(y_true, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_true, y_pred))

# لكل نتيجة (صورة)
for result in results:
    # result.boxes, result.masks, result.keypoints
    img = result.plot()  # هذا يضيف كل boxes على الصورة
    # لو تحب تميز right_place=True بلون معين
    # مثال: Boxes اللي عندها right_place=True بلون أخضر، وFalse أحمر
    for box, right_place in zip(result.boxes.xyxy, result.boxes.cls):
        color = (0,255,0) if right_place==1 else (255,0,0)
        x1, y1, x2, y2 = map(int, box)
        cv2.rectangle(img, (x1,y1), (x2,y2), color, 2)

    # عرض الصورة
    cv2.imshow("Prediction", img)
    cv2.waitKey(0)  # اضغط أي زر للانتقال للصورة التالية
cv2.destroyAllWindows()

# print("عدد الـ 1 في ground truth:", sum(y_true))
# print("عدد الـ 1 في prediction  :", sum(y_pred))

# import glob

# # 1. Setup paths
# test_images = glob.glob('/kaggle/input/dal-shemagh-detection-challenge/images/test/*.jpg')
# submission_data = []


# # 3. Inference Loop
# print(f"Processing {len(test_images)} images...")

# for img_path in tqdm(test_images):
#     filename = os.path.basename(img_path)

#     # Run inference
#     results = model.predict(img_path, conf=0.25, verbose=False)[0]

#     prediction_strings = []
#     person_boxes = []
#     shemagh_boxes = []

#     # Process detections
#     if len(results.boxes) == 0:
#         prediction_str = "-"
#         right_place = 0
#     else:
#         for box in results.boxes:
#             # Extract data
#             cls = int(box.cls[0])
#             conf = float(box.conf[0])

#             # YOLO returns xywh normalized if we access .xywhn
#             x, y, w, h = box.xywhn[0].tolist()

#             # Append to prediction string
#             prediction_strings.append(f"{cls} {conf:.4f} {x:.4f} {y:.4f} {w:.4f} {h:.4f}")

#             # Store boxes for logic check
#             if cls == 0: # Assuming 0 is Person
#                 person_boxes.append([x, y, w, h])
#             elif cls == 1: # Assuming 1 is Shemagh
#                 shemagh_boxes.append([x, y, w, h])

#         prediction_str = " ".join(prediction_strings)

#         # --- LOGIC FOR "RIGHT PLACE" ---
#         # Heuristic: If we found at least one person and one shemagh
#         # and they overlap (IoU > threshold), predict 1.

#         right_place = 0 # Default to 0
#         if person_boxes and shemagh_boxes:
#             # Check every shemagh against every person
#             for s_box in shemagh_boxes:
#                 for p_box in person_boxes:
#                     iou = calculate_iou(s_box, p_box)
#                     # Threshold: 0.1 means 10% overlap. Adjust this based on validation!
#                     if iou > 0.1:
#                         right_place = 1
#                         break
#                 if right_place == 1:
#                     break

#     submission_data.append([filename, right_place, prediction_str])

# # 4. Save to CSV
# df_sub = pd.DataFrame(submission_data, columns=['filename', 'right_place', 'prediction_string'])
# df_sub.to_csv('submission.csv', index=False)

# print("Submission.csv generated successfully!")
# print(df_sub.head(20))

vall_images = glob.glob(f'{WORK_DIR}/images/val/*.jpg')
print(f"Found {len(vall_images)} validation images.")

# import cv2
# import matplotlib.pyplot as plt
# import os

# # تابع لتحويل xywh normalized إلى إحداثيات الصورة
# def xywh_to_xyxy(box, img_shape):
#     x, y, w, h = box
#     h_img, w_img, _ = img_shape
#     x1 = int((x - w/2) * w_img)
#     y1 = int((y - h/2) * h_img)
#     x2 = int((x + w/2) * w_img)
#     y2 = int((y + h/2) * h_img)
#     return x1, y1, x2, y2

# # عرض أول 5 صور right_place = 1
# count = 0
# for filename, right_place, pred_str in submission_data:
#     if right_place == True:
#         img_path = os.path.join(WORK_DIR, "images/train", filename)
#         img = cv2.imread(img_path)
#         if img is None:
#             print(f"⚠️ Could not read image: {filename}")
#             continue

#         # رسم الـ bounding boxes
#         if pred_str != "-":
#             parts = pred_str.split()
#             for i in range(0, len(parts), 6):
#                 cls = int(parts[i])
#                 x, y, w, h = map(float, parts[i+2:i+6])
#                 x1, y1, x2, y2 = xywh_to_xyxy([x, y, w, h], img.shape)
#                 color = (0,255,0) if cls == 0 else (255,0,0)
#                 cv2.rectangle(img, (x1,y1), (x2,y2), color, 2)

#         plt.figure(figsize=(8,8))
#         plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
#         plt.title(f"Right Place! Image: {filename}")
#         plt.axis('off')
#         plt.show()

#         count += 1
#     if count >= 5:
#         break

import glob

# 1. Setup paths
test_images = glob.glob('/kaggle/input/dal-shemagh-detection-challenge/images/test/*.jpg')
submission_data = []
def calculate_iou(box1, box2):
    """
    Calculate IoU between two boxes (x, y, w, h normalized).
    """
    # Convert from xywh to x1, y1, x2, y2
    b1_x1, b1_x2 = box1[0] - box1[2]/2, box1[0] + box1[2]/2
    b1_y1, b1_y2 = box1[1] - box1[3]/2, box1[1] + box1[3]/2

    b2_x1, b2_x2 = box2[0] - box2[2]/2, box2[0] + box2[2]/2
    b2_y1, b2_y2 = box2[1] - box2[3]/2, box2[1] + box2[3]/2

    # Intersection coordinates
    inter_x1 = max(b1_x1, b2_x1)
    inter_y1 = max(b1_y1, b2_y1)
    inter_x2 = min(b1_x2, b2_x2)
    inter_y2 = min(b1_y2, b2_y2)

    inter_area = max(0, inter_x2 - inter_x1) * max(0, inter_y2 - inter_y1)
    b1_area = (b1_x2 - b1_x1) * (b1_y2 - b1_y1)
    b2_area = (b2_x2 - b2_x1) * (b2_y2 - b2_y1)

    union_area = b1_area + b2_area - inter_area
    return inter_area / union_area if union_area > 0 else 0

# 3. Inference Loop
print(f"Processing {len(test_images)} images...")

for img_path in tqdm(test_images):
    filename = os.path.basename(img_path)

    # Run inference
    results = model.predict(img_path, conf=0.25,iou=0.7, verbose=False)[0]

    prediction_strings = []
    person_boxes = []
    shemagh_boxes = []

    # Process detections
    if len(results.boxes) == 0:
        prediction_str = "-"
        right_place = 0
    else:
        for box in results.boxes:
            # Extract data
            cls = int(box.cls[0])
            conf = float(box.conf[0])

            # YOLO returns xywh normalized if we access .xywhn
            x, y, w, h = box.xywhn[0].tolist()

            # Append to prediction string
            prediction_strings.append(f"{cls} {conf:.4f} {x:.4f} {y:.4f} {w:.4f} {h:.4f}")

            # Store boxes for logic check
            if cls == 0: # Assuming 0 is Person
                person_boxes.append([x, y, w, h])
            elif cls == 1: # Assuming 1 is Shemagh
                shemagh_boxes.append([x, y, w, h])

        prediction_str = " ".join(prediction_strings)

        # --- LOGIC FOR "RIGHT PLACE" ---
        # Heuristic: If we found at least one person and one shemagh
        # and they overlap (IoU > threshold), predict 1.

        right_place = 0 # Default to 0
        if person_boxes and shemagh_boxes:
            # Check every shemagh against every person
            for s_box in shemagh_boxes:
                for p_box in person_boxes:
                    iou = calculate_iou(s_box, p_box)
                    # Threshold: 0.1 means 10% overlap. Adjust this based on validation!
                    if iou > 0.1:
                        right_place = 1
                        break
                if right_place == 1:
                    break

    submission_data.append([filename, right_place, prediction_str])

# 4. Save to CSV
df_sub = pd.DataFrame(submission_data, columns=['filename', 'right_place', 'prediction_string'])
df_sub.to_csv('submission.csv', index=False)

print("Submission.csv generated successfully!")
print(df_sub.head(20))

# import os

# weights_dir = "/kaggle/working/runs/detect/dal_challenge/shemagh_detector_rtdetr"

# if os.path.exists(weights_dir):
#     files = os.listdir(weights_dir)
#     if files:
#         print("✅ تم حفظ الملفات التالية:", files)
#     else:
#         print("❌ المجلد موجود لكن لا يوجد ملفات موديل محفوظة!")
# else:
#     print("❌ لم يتم إنشاء المجلد بعد!")



